services:
  - type: web
    name: parcelas-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn parcelas_backend.wsgi:application"
    envVars:
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.3"
