# Generated by Django 6.0.7 on 2026-07-22 02:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_lote', models.CharField(max_length=50)),
                ('numero_rol', models.CharField(blank=True, max_length=50, null=True)),
                ('subdivision', models.CharField(max_length=100)),
                ('superficie_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('vendida', 'Vendida')], default='disponible', max_length=20)),
            ],
            options={
                'db_table': 'parcelas',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('pie_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cuotas', models.IntegerField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('incumplido', 'Incumplido')], default='activo', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.cliente')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.parcela')),
            ],
            options={
                'db_table': 'contratos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_cuota', models.IntegerField()),
                ('monto_cobrar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.contrato')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
    ]
