# Generated by Django 6.0.7 on 2026-07-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='estado_calculado',
            field=models.CharField(choices=[('current', 'Current'), ('overdue', 'Overdue'), ('inactive', 'Inactive')], default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='contrato',
            name='installment_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contrato',
            name='proximo_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contrato',
            name='ultimo_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
