# Generated by Django 6.0.7 on 2026-07-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuariopermitido'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='en_papelera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcela',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
