# Generated by Django 6.0.7 on 2026-07-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_parcela_en_papelera_parcela_fecha_eliminacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fecha_firma',
            field=models.DateField(blank=True, null=True),
        ),
    ]
