# Generated by Django 6.0.7 on 2026-07-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_subdivision_parcela_subdivision_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='tipo_pago',
            field=models.CharField(choices=[('contado', 'Al Contado'), ('credito', 'Con Cuotas')], default='credito', max_length=20),
        ),
    ]
