# Generated by Django 6.0.7 on 2026-08-06 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contrato_tipo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_firma',
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='superficie_m2',
        ),
    ]
