# Generated by Django 6.0.7 on 2026-09-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_contrato_fecha_firma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='en_papelera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
